# Generated by Django 3.0.4 on 2020-03-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
