# Generated by Django 3.0.4 on 2020-04-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('compro', models.BooleanField(default=False)),
                ('vendedor', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.CharField(max_length=400)),
                ('comentarios', models.TextField()),
            ],
        ),
    ]
