# Generated by Django 3.0.4 on 2020-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesados', '0002_auto_20200401_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesado',
            name='modificado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
