# Generated by Django 3.0.4 on 2020-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesados', '0004_auto_20200401_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesado',
            name='ciudad',
            field=models.CharField(default='Juticalpa', max_length=50),
        ),
    ]
