# Generated by Django 3.0.4 on 2020-04-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interesados', '0005_interesado_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesado',
            name='estatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
